version: "3"
services:
  backend:
    build: .
    restart: always
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"
    volumes:
      - ./files:/app/files
      - ./.config:/app/.config:ro
  db:
    restart: always
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    env_file:
      - .config/docker.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20
