-- migrate:up
CREATE TABLE users (
    uid VARCHAR PRIMARY KEY,
    id VARCHAR(15) NOT NULL,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
);

CREATE UNIQUE INDEX idx_users_id ON users (id);

CREATE TABLE shouts (
    ulid VARCHAR NOT NULL PRIMARY KEY,
    uid TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    CONSTRAINT FOREIGN KEY fk_shouts_uid (uid) REFERENCES users (uid)
)

-- migrate:down

DROP TABLE shouts;
DROP INDEX idx_users_id ON users;
DROP TABLE users;
